### ISSUE TITLE
Group-Chat Support

### ISSUE THREAD

**Issue by amiruqdah** [bsansouci/marc-zuckerbot#3]
Hey!

I was playing around with the source a couple of hours ago and I noticed that the bot didn't work in a group chat? Have I set something up incorrectly or is that normal behavior?

**Comment by bsansouci** [comment]
Hey @amiruqdaj, no that's definitely abnormal. Could you expand what you mean by "didn't work in a group chat"?

**Comment by amiruqdah** [comment]
I tried the sample you guys had, and it didn't exactly work when I threw the bot in a group chat setting. I did have a poke around in the source so perhaps I changed something. I just started writing my own bot with the API and it works perfectly(even in group chat settings), but I'm trying to read a "log:subscribe" event, but I can't get to log_message_data without it returning an "Unexpected Token N". Is the JSON data malformed, here?

**Comment by Schmavery** [comment]
Can you revert your changes and run it again?  We actually have Marc running 24/7, so it's hard to imagine there being a problem.

**Comment by amiruqdah** [comment]
@Schmavery I'm terribly sorry for just leaving this open like this. I ended up fixing it and it worked as intended =)

**Comment by bsansouci** [comment]
Nice. Closing then ;)

**Comment by bsansouci** [comment]
Btw check out the future of marc: https://github.com/bsansouci/lisp-bot

**Comment by amiruqdah** [comment]
:fire:  :fire_engine:  is that Lisp in JS?

**Comment by bsansouci** [comment]
It's a small lisp interpreter yeah ;)
So we get the flexibility to customize the bot, and we get some sort of guarantee that people can't mess around too much :p
